window.KAZU_DIALOGUES = [
  { id:'new_game_01', condition:'new_game', priority:60, once:true, dialogues:['よう、目ぇ覚めたか。ここが俺の店や、しばらく世話になり。','まずは近くのダンジョンで慣れとき。飯は出す、死なんと帰ってきいや。'] },
  // 序盤はカズ自身を連打する隠し導線と、PHANTOM SHOPの存在を段階的に案内する。
  // 3件を別のonce台詞にして、初回説明の後から数回にわたって高頻度で出す。
  { id:'early_phantom_shop_01', condition:'early_phantom_shop', priority:59, once:true, dialogues:['俺に触っても意味ないからな？ ……一回だけなら、やけど。'] },
  { id:'early_phantom_shop_02', condition:'early_phantom_shop', priority:58, once:true, dialogues:['この店、表に出してへん品もある。俺を三回つついたら《PHANTOM SHOP》を見せたるわ。'] },
  { id:'early_phantom_shop_03', condition:'early_phantom_shop', priority:57, once:true, dialogues:['時短したいなら《PHANTOM SHOP》や。俺を三回タップして、買い物を選び。音ゲーもそこから入れるで。'] },
  { id:'after_first_battle_01', condition:'after_first_battle', priority:50, once:false, dialogues:['生きて帰ってきたやん。上出来やで。','初戦でそれなら悪うない。続けりゃちゃんと強うなるわ。','腹減ったまま潜ったらあかんで。まず食べてき。'] },
  { id:'low_hp_01', condition:'low_hp', priority:70, once:false, dialogues:['そのHPで行く気かいな。まかない食べてからおいでや。','無茶したらあかん。回復して、装備も見直しとき。','死ぬより一杯食う方が安うつく。ほんまやで。'] },
  { id:'consecutive_defeats_01', condition:'consecutive_defeats', priority:75, once:false, dialogues:['負けが続いとるな。焦らんでええ、装備と技を組み直そか。','怪異は逃げへん。育てて、作って、もう一回や。','考えて勝つんが怪盗やろ。気合いだけではあきまへんがな。'] },
  { id:'just_defeated_01', condition:'just_defeated', priority:65, once:false, dialogues:['また運び込まれてきたんか。生きとるならそれでええ。','座り。メシ食べ。話はそれからや。','悔しいんは次に持っていき。帰ってきた時点で負けっぱなしやない。'] },
  { id:'workshop_just_unlocked_01', condition:'workshop_just_unlocked', priority:80, once:true, dialogues:['工房、使えるようになったで。素材集めて好きに鍛えや。','ノエルに負けた分も無駄やなかったな。遠慮せんと工房使い。'] },
  { id:'workshop_unlocked_01', condition:'workshop_unlocked', priority:12, once:false, dialogues:['工房の調子はどうや。素材、寝かせっぱなしやないやろな。','装備が整うたら戦いも楽になる。こまめに作っとき。'] },
  { id:'has_materials_no_workshop_01', condition:'has_materials_no_workshop', priority:30, once:false, dialogues:['なんや、ええもん拾うてきたな。今は取っとき、後で化けるで。','素材は裏切らへん。たぶんやけどな。'] },
  { id:'weapon_fusion_unlocked_01', condition:'weapon_fusion_unlocked', priority:35, once:true, dialogues:['武器強化も開いたで。欲張りすぎたら泣くで、気ぃつけや。','俺なら慎重にやるなぁ。まあ、お前は好きにやり。'] },
  { id:'boss1_available_01', condition:'boss1_available', priority:55, once:false, dialogues:['反応が出とる。あれは普通やないで、準備万端で行き。','行くんは止めへん。せやけど全回復してからや、ええな。'] },
  { id:'boss1_cleared_01', condition:'boss1_cleared', priority:12, once:false, dialogues:['あの経験が今のお前を作っとる。忘れんとき。','工房も使える。ここからが腕の見せどころやで。'] },
  { id:'zenakado_available_01', condition:'zenakado_available', priority:58, once:false, dialogues:['ゼナカドは強いで。装備と技、出せるもん全部出して行き。','あの旋律を止められるんはお前や。ほな、頼んだで。'] },
  { id:'zenakado_cleared_first_01', condition:'zenakado_cleared_first', priority:85, once:true, dialogues:['ゼナカド倒したんか……ほんま大したもんや。新しいメニュー考えたさかい、食ってけ。','札幌味噌ラーメン、今日から出したるわ。これで戦いも楽になるやろ、装備のために頑張りや。'] },
  { id:'zenakado_cleared_01', condition:'zenakado_cleared', priority:14, once:false, dialogues:['ジョブも増えたし、戦い方の幅が広がったなぁ。','次の迷宮は準備してから行き。無茶もほどほどにな。'] },
  { id:'dungeon2_available_01', condition:'dungeon2_available', priority:52, once:true, dialogues:['新しいダンジョンが開いたで。何がおるか分からへん、気ぃつけや。','おいでやす、ダンジョン2へ。……京都ちゃうけどな。'] },
  { id:'dungeon2_first_return', condition:'dungeon2_first_return', priority:48, once:true, dialogues:['ダンジョン2の感触はどうや。慣れるまで無理したらあかん。','素材も変わってくる。集めながらゆっくり攻略し。'] },
  { id:'dungeon2_floor1_chat', condition:'dungeon2_floor1', priority:25, once:false, dialogues:['残響の回廊か。音に気ぃ取られたら、足元すくわれるで。','D1の装備だけで押し切らんと、拾った素材はちゃんと工房へ持っていき。','敵が硬う感じたら、武器学と技の組み合わせを見直してみ。'] },
  { id:'dungeon2_floor2_chat', condition:'dungeon2_floor2', priority:25, once:false, dialogues:['沈黙の広間まで来たか。静かな場所ほど、嫌な気配はよう響く。','二階からは敵の組み合わせも面倒や。倒す順番、決めてから動き。','同じ装備が余っとるなら強化用に残しとき。売るんは後でもできる。'] },
  { id:'dungeon2_floor3_chat', condition:'dungeon2_floor3', priority:25, once:false, dialogues:['最奥が近いな。ここから先は速さ負けしたら一気に持っていかれるで。','装備だけやのうて、素早さと技の初動も見とき。先に動けるんは立派な強さや。','楽殿の奥、えらい鋭い気配がしとる。帰れる余力は残しときや。'] },
  { id:'myrthi_available_01', condition:'myrthi_available', priority:56, once:false, dialogues:['ミルティは速いで。素早さで負けたら、なんも出来ひんかもしれん。','行くなら今の実力、ちゃんと測ってからにし。'] },
  { id:'myrthi_cleared_first_01', condition:'myrthi_cleared_first', priority:83, once:true, dialogues:['ミルティを倒したんか。あの速さを超えたなら、たいした怪盗や。','双刃戦姫を落とすとはなぁ。うち、ちょっと感心してもうたわ。'] },
  { id:'myrthi_cleared_01', condition:'myrthi_cleared', priority:14, once:false, dialogues:['双刃士も使えるようになったな。いろいろ試してみ。','MYRTHIシリーズ、ええ仕上がりやろ。使い倒しや。'] },
  { id:'dungeon3_available_01', condition:'dungeon3_available', priority:82, once:true, dialogues:['次の迷宮、開いたみたいやな。今までと空気がちゃう、装備の確認は念入りにし。','崩界の深廊か……名前からして帰す気ないやろ。無茶する前に、戻る判断も覚えとき。'] },
  { id:'dungeon3_first_return_01', condition:'dungeon3_first_return', priority:50, once:true, dialogues:['ちゃんと帰ってきたな。D3は一気に抜ける場所やない、階ごとに仕上げていき。','あそこの怪異、守り方に癖があるやろ。物理と魔法、片方だけに頼ったらしんどいで。'] },
  { id:'dungeon3_early_chat', condition:'dungeon3_early', priority:25, once:false, dialogues:['外壁と中庭は見極めの階や。効かん攻撃を意地で振り続けたらあかん。','D2装備で苦しいなら正常や。新しい素材を拾って、一つずつ更新していき。','二体、三体と並んだ時は支援役から崩すんも手やで。'] },
  { id:'dungeon3_midway_chat', condition:'dungeon3_midway', priority:25, once:false, dialogues:['封鎖門の先、妙な銀の音が混じっとる。ボス前やと思うて準備し。','三階、四階はMPの使い方が大事や。毎戦全力やと先に息切れするで。','鎖の回廊まで来たんやな。回復と防壁を使う怪異は、放っとくと長引くで。'] },
  { id:'versicrell_available_01', condition:'versicrell_available', priority:58, once:false, dialogues:['銀の輪が道を塞いどる。あれ、倒した思うて気ぃ抜いたらあかん類や。','ヴェルシクレルの演奏は一曲で終わらへん。最後まで立っとるつもりで行き。'] },
  { id:'versicrell_cleared_first_01', condition:'versicrell_cleared_first', priority:84, once:true, dialogues:['銀環を二度とも砕いたんか。見た目よりしぶとい相手やったな。ようやった。','あの異奏を止めたなら後半へ進める。せやけど、ここから敵の圧が一段上がるで。'] },
  { id:'dungeon3_late_chat', condition:'dungeon3_late', priority:25, once:false, dialogues:['礼拝堂から先は別もんや。火力だけやのうて、耐える準備も要るで。','深紅の塔まで来たら装備の穴が命取りや。防御も魔法防御も見直し。','ここからは短く倒す力も必要や。長引くほど向こうが有利になる。'] },
  { id:'dungeon3_final_chat', condition:'dungeon3_final', priority:25, once:false, dialogues:['奈落の奏廊まで来たか。最奥へ持っていく技、そろそろ絞っとき。','玉座へ行く前に、回復手段とパッシブをもう一度確認し。準備も実力のうちや。','白い盾の気配がする。強い一撃を返してくる相手なら、攻め方にも工夫が要るな。'] },
  { id:'seripes_available_01', condition:'seripes_available', priority:58, once:false, dialogues:['最奥の盾が待っとるで。力押しだけやと、殴った分まで返されるかもしれん。','セリペスに挑むなら、強い一発と弱い一発、両方使い分けるつもりで行き。'] },
  { id:'seripes_cleared_first_01', condition:'seripes_cleared_first', priority:86, once:true, dialogues:['不落の盾まで盗み切ったか。もう新人扱いはできへんな。','D3踏破、おめでとうさん。けど、お前の道はまだ先へ続いとるみたいやで。'] },
  { id:'dungeon3_cleared_chat', condition:'dungeon3_cleared', priority:25, once:false, dialogues:['D3を越えた今なら、前の階で試したい戦い方もあるやろ。好きに暴れてき。','セリペスの盾、使いこなせば攻めにもなる。守るだけが盾やないで。','ここまで来ても、飯と準備は忘れたらあかん。強い奴ほど基本を雑にせえへん。'] },
  { id:'job_unlocked', condition:'job_unlocked', priority:42, once:true, dialogues:['JOBが使えるようになったで。組み合わせで化けるさかい、よう考えや。','得意なことは職ごとにちゃう。食わず嫌いせんと試し。'] },
  { id:'job_mastered', condition:'job_mastered', priority:18, once:false, dialogues:['JOBマスターかいな。そら強うなっとるわ。','Lv20まで育てたんやったら、次の道も見えてくるで。'] },
  { id:'workshop_used', condition:'workshop_used', priority:11, once:false, dialogues:['ちゃんと工房使うとるな。それが近道やで。','自分で作った装備は大事にし。壊したら泣くで。'] },
  { id:'reni_chat', condition:'reni_chat', priority:10, once:false, dialogues:['工房、助かっとるか。整備するん、結構骨折れたんやで。','帰るたんび成長しとるな。俺には分かるんや、ほんま。'] },
  { id:'ramen_chat', condition:'ramen_chat', priority:8, once:false, dialogues:['今日のスープ、ええ塩梅や。食べてみ。','ラーメン一杯で世界は変わらへん。でも腹は変わる。まず食べ。','麺の茹で時間は命や。戦闘の判断も似たようなもんやろ。'] },
  { id:'meta_chat', condition:'meta_chat', priority:5, once:false, dialogues:['最近また腕ぇ上げたんちゃう。顔つきがちゃうわ。','無茶はほどほどにな。でもそれがお前の流儀なら、止めへん。'] },
  { id:'always_01', condition:'always', priority:5, once:false, dialogues:['おかえりや。怪我はあらへんか？……まあ、俺の関西弁は気にすんな。','また来たんか。茶でも入れよか。','ここは安全や、ゆっくりしていき。','なんか用か？なけりゃ飯でも食ってけや。','困ったことあったら言い。出来る範囲で手ぇ貸したる。'] }
];
