window.KAZU_DIALOGUES = [
  { id:'new_game_01', condition:'new_game', priority:60, once:true, dialogues:['よう、目ぇ覚めたか。ここが俺の店や、しばらく世話になり。','まずは近くのダンジョンで慣れとき。飯は出す、死なんと帰ってきいや。'] },
  // 序盤はカズ自身を連打する隠し導線と、PHANTOM SHOPの存在を段階的に案内する。
  // 3件を別のonce台詞にして、初回説明の後から数回にわたって高頻度で出す。
  { id:'early_phantom_shop_01', condition:'early_phantom_shop', priority:59, once:true, dialogues:['俺に触っても意味ないからな？ ……一回だけなら、やけど。'] },
  { id:'early_phantom_shop_02', condition:'early_phantom_shop', priority:58, once:true, dialogues:['この店、表に出してへん品もある。俺を三回つついたら《PHANTOM SHOP》を見せたるわ。'] },
  { id:'early_phantom_shop_03', condition:'early_phantom_shop', priority:57, once:true, dialogues:['時短したいなら《PHANTOM SHOP》や。俺を三回タップして、買い物を選び。音ゲーもそこから入れるで。'] },
  { id:'after_first_battle_01', condition:'after_first_battle', priority:50, once:false, dialogues:['生きて帰ってきたやん。上出来やで。','初戦でそれなら悪うない。続けりゃちゃんと強うなるわ。','腹減ったまま潜ったらあかんで。まず食べてき。'] },
  { id:'low_hp_01', condition:'low_hp', priority:70, once:false, dialogues:['そのHPで行く気かいな。まかない食べてからおいでや。','無茶したらあかん。回復して、装備も見直しとき。','死ぬより一杯食う方が安うつく。ほんまやで。'] },
  { id:'consecutive_defeats_01', condition:'consecutive_defeats', priority:75, once:false, dialogues:['負けが続いとるな。焦らんでええ、装備と技を組み直そか。','怪異は逃げへん。育てて、作って、もう一回や。','考えて勝つんが怪盗やろ。気合いだけではあきまへんがな。'] },
  { id:'just_defeated_01', condition:'just_defeated', priority:65, once:false, dialogues:['また運び込まれてきたんか。生きとるならそれでええ。','座り。メシ食べ。話はそれからや。','悔しいんは次に持っていき。帰ってきた時点で負けっぱなしやない。'] },
  { id:'workshop_just_unlocked_01', condition:'workshop_just_unlocked', priority:80, once:true, dialogues:['工房、使えるようになったで。素材集めて好きに鍛えや。','ノエルに負けた分も無駄やなかったな。遠慮せんと工房使い。'] },
  { id:'workshop_unlocked_01', condition:'workshop_unlocked', priority:20, once:false, dialogues:['工房の調子はどうや。素材、寝かせっぱなしやないやろな。','装備が整うたら戦いも楽になる。こまめに作っとき。'] },
  { id:'has_materials_no_workshop_01', condition:'has_materials_no_workshop', priority:30, once:false, dialogues:['なんや、ええもん拾うてきたな。今は取っとき、後で化けるで。','素材は裏切らへん。たぶんやけどな。'] },
  { id:'weapon_fusion_unlocked_01', condition:'weapon_fusion_unlocked', priority:35, once:true, dialogues:['武器強化も開いたで。欲張りすぎたら泣くで、気ぃつけや。','俺なら慎重にやるなぁ。まあ、お前は好きにやり。'] },
  { id:'boss1_available_01', condition:'boss1_available', priority:55, once:false, dialogues:['反応が出とる。あれは普通やないで、準備万端で行き。','行くんは止めへん。せやけど全回復してからや、ええな。'] },
  { id:'boss1_cleared_01', condition:'boss1_cleared', priority:45, once:false, dialogues:['あの経験が今のお前を作っとる。忘れんとき。','工房も使える。ここからが腕の見せどころやで。'] },
  { id:'zenakado_available_01', condition:'zenakado_available', priority:58, once:false, dialogues:['ゼナカドは強いで。装備と技、出せるもん全部出して行き。','あの旋律を止められるんはお前や。ほな、頼んだで。'] },
  { id:'zenakado_cleared_first_01', condition:'zenakado_cleared_first', priority:85, once:true, dialogues:['ゼナカド倒したんか……ほんま大したもんや。新しいメニュー考えたさかい、食ってけ。','札幌味噌ラーメン、今日から出したるわ。これで戦いも楽になるやろ、装備のために頑張りや。'] },
  { id:'zenakado_cleared_01', condition:'zenakado_cleared', priority:40, once:false, dialogues:['ジョブも増えたし、戦い方の幅が広がったなぁ。','次の迷宮は準備してから行き。無茶もほどほどにな。'] },
  { id:'dungeon2_available_01', condition:'dungeon2_available', priority:52, once:true, dialogues:['新しいダンジョンが開いたで。何がおるか分からへん、気ぃつけや。','おいでやす、ダンジョン2へ。……京都ちゃうけどな。'] },
  { id:'dungeon2_first_return', condition:'dungeon2_first_return', priority:48, once:false, dialogues:['ダンジョン2の感触はどうや。慣れるまで無理したらあかん。','素材も変わってくる。集めながらゆっくり攻略し。'] },
  { id:'myrthi_available_01', condition:'myrthi_available', priority:56, once:false, dialogues:['ミルティは速いで。素早さで負けたら、なんも出来ひんかもしれん。','行くなら今の実力、ちゃんと測ってからにし。'] },
  { id:'myrthi_cleared_first_01', condition:'myrthi_cleared_first', priority:83, once:true, dialogues:['ミルティを倒したんか。あの速さを超えたなら、たいした怪盗や。','双刃戦姫を落とすとはなぁ。うち、ちょっと感心してもうたわ。'] },
  { id:'myrthi_cleared_01', condition:'myrthi_cleared', priority:38, once:false, dialogues:['双刃士も使えるようになったな。いろいろ試してみ。','MYRTHIシリーズ、ええ仕上がりやろ。使い倒しや。'] },
  { id:'job_unlocked', condition:'job_unlocked', priority:42, once:true, dialogues:['JOBが使えるようになったで。組み合わせで化けるさかい、よう考えや。','得意なことは職ごとにちゃう。食わず嫌いせんと試し。'] },
  { id:'job_mastered', condition:'job_mastered', priority:44, once:false, dialogues:['JOBマスターかいな。そら強うなっとるわ。','Lv20まで育てたんやったら、次の道も見えてくるで。'] },
  { id:'workshop_used', condition:'workshop_used', priority:22, once:false, dialogues:['ちゃんと工房使うとるな。それが近道やで。','自分で作った装備は大事にし。壊したら泣くで。'] },
  { id:'reni_chat', condition:'reni_chat', priority:10, once:false, dialogues:['工房、助かっとるか。整備するん、結構骨折れたんやで。','帰るたんび成長しとるな。俺には分かるんや、ほんま。'] },
  { id:'ramen_chat', condition:'ramen_chat', priority:8, once:false, dialogues:['今日のスープ、ええ塩梅や。食べてみ。','ラーメン一杯で世界は変わらへん。でも腹は変わる。まず食べ。','麺の茹で時間は命や。戦闘の判断も似たようなもんやろ。'] },
  { id:'meta_chat', condition:'meta_chat', priority:5, once:false, dialogues:['最近また腕ぇ上げたんちゃう。顔つきがちゃうわ。','無茶はほどほどにな。でもそれがお前の流儀なら、止めへん。'] },
  { id:'always_01', condition:'always', priority:5, once:false, dialogues:['おかえりや。怪我はあらへんか？……なんや、この関西弁ないけどな。','また来たんか。茶でも入れよか。','ここは安全や、ゆっくりしていき。','なんか用か？なけりゃ飯でも食ってけや。','困ったことあったら言い。出来る範囲で手ぇ貸したる。'] }
];
